
- name: Run diksha table_definitions from SQL script
  become: true
  become_user: postgres
  postgresql_query:
    db: "{{ db_name }}"
    path_to_script: /tmp/postgres/diksha.sql
  when: diksha
  tags: [ install, update ]

- name: Run diksha queries from SQL script
  become: true
  become_user: postgres
  postgresql_query:
    db: "{{ db_name }}"
    path_to_script: /tmp/postgres/diksha_queries.sql
  when: diksha
  tags: [ install, update ]
