---
- name: Creating config file
  file:
    path: "{{ base_dir }}/cqube/.cqube_config"
    state: touch
    mode: u+rw,g+rw,o+rw
  tags: install
    
- name: Loading required data inside config file
  blockinfile:
        path: "{{ base_dir }}/cqube/.cqube_config"
        marker: "# {mark} workflow MARKER"
        block: |
               CQUBE_WORKFLOW_VERSION={{ cqube_workflow_version }}
               CQUBE_USECASE_NAME={{ usecase_name }}
               CQUBE_STATE_CODE={{ state_code }}
               CQUBE_STATIC_DATASOURCE={{ static_datasource }}
  tags: install

- name: Updating the CQUBE_VERSION
  lineinfile: 
    regex: '^CQUBE_WORKFLOW_VERSION='
    line: CQUBE_WORKFLOW_VERSION={{ cqube_workflow_version }}
    path: "{{ base_dir }}/cqube/.cqube_config"
  tags: update
