- name: Run crc python code
  shell: "{{ base_dir }}/cqube/emission_app/flaskenv/bin/python {{ base_dir }}/cqube/emission_app/python/deploy_nifi.py crc_transformer crc_parameters 4660"
  tags: [ install, update ]

- name: Connection of crc to cqube data storage
  shell: "{{ base_dir }}/cqube/emission_app/flaskenv/bin/python {{ base_dir }}/cqube/emission_app/python/connect_nifi_processors.py cQube_data_storage crc_transformer"
  tags: [ install, update ]

- name: run python code to disable the processors
  shell: "{{ base_dir }}/cqube/emission_app/flaskenv/bin/python {{ base_dir }}/cqube/emission_app/python/nifi_disable_processor.py crc_transformer {{ storage_type }}"
  tags: [ install, update ]
  
