
- name: Run crc table_definitions from SQL script
  become: true
  become_user: postgres
  postgresql_query:
    db: "{{ db_name }}"
    path_to_script: /tmp/postgres/crc.sql
  when: crc
  tags: [ install, update ]

- name: Run crc queries from SQL script
  become: true
  become_user: postgres
  postgresql_query:
    db: "{{ db_name }}"
    path_to_script: /tmp/postgres/crc_queries.sql
  when: crc
  tags: [ install, update ]
