- name: Run infra python code
  shell: "{{ base_dir }}/cqube/emission_app/flaskenv/bin/python {{ base_dir }}/cqube/emission_app/python/deploy_nifi.py infra_transformer infra_parameters 4661"
  tags: [ install, update ]

- name: Connection of infra to cqube data storage
  shell: "{{ base_dir }}/cqube/emission_app/flaskenv/bin/python {{ base_dir }}/cqube/emission_app/python/connect_nifi_processors.py cQube_data_storage infra_transformer"
  tags: [ install, update ]
