
#- name: Run progresscard table_definitions from SQL script
# become: true
# become_user: postgres
# postgresql_query:
#   db: "{{ db_name }}"
#   path_to_script: /tmp/postgres/progresscard.sql
# when: progresscard
# tags: [ install, update ]

- name: Run progresscard queries from SQL script
  become: true
  become_user: postgres
  postgresql_query:
    db: "{{ db_name }}"
    path_to_script: /tmp/postgres/progress_card_queries.sql
  when: progresscard
  tags: [ install, update ]
