import * as config from '../../assets/config.json';
import { environment } from '../../environments/environment';

let state = config.default[`${environment.stateName}`].name;
export const dashboardReportDescriptions = {
    imrTooltip: "This geo-location-based dashboard provides insights on school infrastructure access across " + state + ".",
    crTooltip: "This dashboard allows users to correlate metrics on school infrastructure data using the scatter plot and table provided.",
    udiseTooltip: "This dashboard converts UDISE data into actionable indices visualized at various administrative levels across " + state + " on a map.",
    compositeTooltip: "This dashboard brings metrics from other dashboards and allows users to correlate various metrics among each other.",
    dscTooltip: "This dashboard provides insights on grade and subject-wise consumption of TPD courses broken by user type.",
    dccTooltip: "This dashboard provides insight on district-wise usage of TPD courses",
    utTooltip: "This dashboard provides insights on district-wise usage of ETB",
    dtrTooltip: "This dashboard provides insights on total usage at the course content level.",
    utcTooltip: "This dashboard provides insights on the total usage at the ETB content level.",
    crcrTooltip: "This dashboard allows users to correlate metrics calculated from the CRC visit data by using the scatter plot and table provided.",
    srTooltip: "This geo-location-based dashboard provides insights on student semester performance across " + state + ".",
    patTooltip: "This geo-location-based dashboard provides insights on student Periodic Assessment Test (PAT) performance across " + state + ".",
    semExpTooltip: "This geo-location-based dashboard provides insights on those schools that did not upload their semester scores.",
    isdataTooltip: "This dashboard allows you to download exception reports for the different dashboards available on cQube",
    sarTooltip: "This geo-location-based dashboard provides insights on Student Attendance across " + state + ".",
    tarTooltip: "This geo-location-based dashboard provides insights on Teacher Attendance across " + state + ".",
    telemDataTooltip: "This dashboard provides insights on usage statistics for cQube",
    heatChartTooltip: "This dashboard provides insights on student performance at the question level.",
    lotableTooltip: "This dashboard provides insights on student performance at the learning outcome level.",
    tpdtpTooltip: "This dashboard provides details on district-wise TPD course enrolment progress broken at the individual course level.",
    tpdcpTooltip: "This dashboard provides details on district-wise TPD course enrolment progress broken at the individual course level.",
    progressCardTooltip: "This dashboard brings metrics from other dashboards and allows users to correlate various metrics among each other.",
    patExcptTooltip: "This geo-location-based dashboard provides insights on those schools that did not upload their periodic assessment scores.",
    tarExpTooltip: "This geo-location-based dashboard provides insights on those schools that did not upload their teacher attendance data.",
    sarExcptTooltip: "This geo-location-based dashboard provides insights on those schools that did not upload their student attendance data.",
    satTooltip: "This geo-location-based dashboard provides insights on student Periodic Assessment Test (SAT) performance across " + state + ".",
    satHeatChartTooltip: "This dashboard provides insights on student performance at the question level.",
    gpsOfLearningTPDTooltip : "The dashboard provides details on the total content plays for Teacher Professional Development (TPD) by location for"+ " " + state + ".",
    gpsOfLearningETBTooltip :"The dashboard provides details on the total content plays for Energised Textbooks (ETB) by location for" + state + ".",
    heartbeatOfTheNationLearning : "The dashboard provides a macro overview of the total content plays over the last two academic years for" + state + ".",
    userOnboarding :"The dashboards provides insights on the user onboarding progress across various TPD courses for" + state + " over time",
    userProgress : "The dashboard provides insights on user onboarding, completion and certification across various TPD courses for"+ " " + state +".",
    userEngagement : "The dashboard provides insights on user engagement for various TPD courses for" + " "+ state +".",
    usagePerCapita : "The dashboard provides the total content play metric over last academic year and current academic year across various districts for "+ state + " normalised using the total eligible population (Total number of students and teachers) for the respective district.",
    contentPreference : "The dashboard provides insights on user's preference (as measured by total content play) by content type across districts for" + " "+ state + ".",
}